/* Merkezi quiz veri dosyası: yeni soruları burada güncelleyin. */
(function () {
const linux_basic = [
            { q: "pwd komutu ne yapar?", opts: ["Disk kullanımını gösterir", "Geçerli dizinin yolunu yazar", "Şifre değiştirir", "Süreçleri listeler"], a: 1 },
            { q: "Gizli dosyaları listelemek için doğru komut?", opts: ["ls -l", "ls -h", "ls -a", "ls --hidden-only"], a: 2 },
            { q: "chmod 755 bir dizinde ne ifade eder?", opts: ["Sahip okur-yazar-çalıştırır, grup/diğerleri okur-çalıştırır", "Herkes tam yetki", "Sadece okuma", "Yalnızca root erişir"], a: 0 },
            { q: "Bir dosyanın sahibini ve grubunu değiştirmek için?", opts: ["chmod user:group dosya", "chown user:group dosya", "chperm user dosya", "usermod dosya"], a: 1 },
            { q: "Bir klasörü içindekilerle kopyalamak için?", opts: ["cp kaynak hedef", "cp -r kaynak hedef", "copy -R", "cp --all"], a: 1 },
            { q: "Bir dosyayı başka dizine taşımak/yeniden adlandırmak için?", opts: ["mv dosya hedef/", "cp dosya hedef/", "rm dosya hedef/", "touch hedef/dosya"], a: 0 },
            { q: "Dizin oluştururken ara dizinleri de açmak için?", opts: ["mkdir dir", "mkdir -p a/b/c", "mkpath", "touch dir"], a: 1 },
            { q: "rm -rf komutu ne yapar?", opts: ["Logları temizler", "Korumalı silme", "Dizini ve içeriğini zorla siler", "Yalnızca boş dizini siler"], a: 2 },
            { q: "Büyük/küçük harf duyarsız arama için grep flag'i?", opts: ["-n", "-v", "-i", "-c"], a: 2 },
            { q: "Log dosyasını gerçek zamanlı izlemek için?", opts: ["tail -f dosya", "head dosya", "cat dosya", "watch dosya"], a: 0 },
            { q: "İlk 20 satırı görmek için?", opts: ["head -n 20 dosya", "tail -20 dosya", "sed -n 1 dosya", "more -20 dosya"], a: 0 },
            { q: "Geçerli dizinde *.log dosyalarını bulmak için?", opts: ["find . -name *.log", "find . -type f -name \"*.log\"", "search *.log", "locate .log"], a: 1 },
            { q: "Geçerli dizinin toplam boyutunu insan okunur göstermek için?", opts: ["df -h .", "du -sh .", "ls -lh .", "stat ."], a: 1 },
            { q: "Disk kullanımını dosya sistemi bazında görmek için?", opts: ["df -h", "du -a", "lsblk", "mount"], a: 0 },
            { q: "Bir klasörü .tar.gz olarak sıkıştırmak için?", opts: ["tar -xzf arşiv.tar.gz klasor", "tar -czvf arşiv.tar.gz klasor", "zip arşiv.tar.gz klasor", "gzip klasor"], a: 1 },
            { q: "Bir .tar.gz arşivini çıkarmak için?", opts: ["tar -xzf arşiv.tar.gz", "tar -czf arşiv.tar.gz", "unzip arşiv.tar.gz", "gunzip arşiv.tar.gz"], a: 0 },
            { q: "Çalışan süreçleri göstermek için yaygın komut?", opts: ["ls -p", "ps aux", "jobs -l", "whoami"], a: 1 },
            { q: "Bir süreci varsayılan sinyalle sonlandırmak için?", opts: ["stop PID", "kill PID (SIGTERM)", "kill -9 PID", "halt PID"], a: 1 },
            { q: "Kullanıcı bilgileri hangi dosyada tutulur?", opts: ["/etc/shadow", "/etc/passwd", "/etc/group", "/etc/hosts"], a: 1 },
            { q: "Varsayılan shell ortamında komut geçmişini filtrelemek için?", opts: ["history | grep komut", "echo $HISTFILE", "cat ~/.history", "grep history"], a: 0 }
        ];
const linux_intermediate = [
            { q: "systemctl status nginx çıktısında hangi bilgi yer alır?", opts: ["Sadece versiyon", "Servis durumu/log özetini", "Port listesi", "Kernel logları"], a: 1 },
            { q: "Bir servisi açılışta başlatmak için doğru komut?", opts: ["systemctl start", "systemctl enable", "service reload", "systemctl run"], a: 1 },
            { q: "Belirli bir servisin loglarını görmek için doğru komut?", opts: ["journalctl -u servis", "logcat servis", "tail /var/log/syslog sadece", "service logs"], a: 0 },
            { q: "Netstat alternatiflerinden listening portları görmek için?", opts: ["netstat -l", "ss -tulpn", "ps -aux", "lsof -i :80"], a: 1 },
            { q: "SSH anahtarının varsayılan yolu nedir?", opts: ["~/.ssh/id_rsa", "/etc/ssh/ssh_host_key", "/var/ssh/key", "~/.ssh/id_ecdsa.pub"], a: 0 },
            { q: "Uzak sunucuya dosya kopyalamak için doğru scp sözdizimi?", opts: ["scp user@host /dosya", "scp dosya user@host:/hedef", "scp host:dosya user", "scp copy remote"], a: 1 },
            { q: "crontab -l ne yapar?", opts: ["Cron servisini başlatır", "Sistem cronlarını resetler", "Geçerli kullanıcının cron görevlerini listeler", "Root cronunu yazar"], a: 2 },
            { q: "Sed ile satır içinde 'eski'yi 'yeni' ile değiştirmek için?", opts: ["sed replace eski yeni", "sed 's/eski/yeni/' dosya", "sed -c eski yeni dosya", "sed -g eski yeni dosya"], a: 1 },
            { q: "Awk ile her satırın ilk kolonu nasıl yazdırılır?", opts: ["awk '{print $0}'", "awk '{print $1}'", "awk print1", "awk -c1"], a: 1 },
            { q: "find . -mtime -1 komutu neyi listeler?", opts: ["Son 1 gün değiştirilmiş dosyaları", "1 MB altı dosyaları", "Son 1 dakika dosyaları", "1 gün önceki dosyaları siler"], a: 0 },
            { q: "xargs komutunun temel amacı?", opts: ["Dosya sistemi formatlamak", "Verilen girdiden komut argümanı üretmek/çalıştırmak", "Log sıkıştırmak", "Port yönlendirmek"], a: 1 },
            { q: "Bir shell değişkenini alt süreçlere aktarmak için?", opts: ["var=1", "set var=1", "export var=1", "declare var=1"], a: 2 },
            { q: "Alias'ı kalıcı yapmak için nereye yazılır?", opts: ["Geçici terminale", "/etc/hosts", "~/.bashrc veya shell config", "/var/log"], a: 2 },
            { q: "Bir sürecin en yüksek CPU kullanımıyla listesini görmek için pratik komut?", opts: ["ps aux --sort=-%cpu | head", "ps -cpu top", "lsproc", "watch ps"], a: 0 },
            { q: "Bir log dosyasının son 100 satırını görmek için?", opts: ["tail dosya", "tail -n 100 dosya", "head -n 100 dosya", "log -100"], a: 1 },
            { q: "SSH ile 2222 portuna bağlanmak için?", opts: ["ssh user@host 2222", "ssh -p 2222 user@host", "ssh user@host -port 2222", "ssh -P user 2222"], a: 1 },
            { q: "whois komutu ne işe yarar?", opts: ["TCP port test", "DNS cache temizleme", "Alan adı kayıt bilgilerini getirir", "ARP tablo gösterir"], a: 2 },
            { q: "Bir log dosyasındaki hata kelimelerini saymak için pratik komut?", opts: ["grep hata log | wc -l", "wc -c hata log", "count hata log", "grep -n log"], a: 0 },
            { q: "Bir kullanıcıyı sudosu olacak şekilde eklemek için hangi grup?", opts: ["wheel/sudo grubuna eklemek", "docker grubuna eklemek", "adm grubuna eklemek", "tty grubuna eklemek"], a: 0 },
            { q: "Hosta statik bir DNS kaydı eklemek için hangi dosya kullanılır?", opts: ["/etc/resolve.conf", "/etc/resolv.conf", "/etc/dns", "/etc/hosts.conf"], a: 1 }
        ];
const linux_advanced = [
            { q: "SELinux mevcut modunu görmek için hangi komut kullanılır?", opts: ["getenforce", "sestatus", "seconfig", "sel show"], a: 0 },
            { q: "SELinux'u geçici olarak permissive yapmak için?", opts: ["setenforce 0", "selinux off", "getenforce 0", "disable selinux"], a: 0 },
            { q: "setcap 'cap_net_bind_service=+ep' /usr/bin/app ne sağlar?", opts: ["HTTP bloklar", "1024 altı portlara root olmadan bind izni", "CPU limiti", "Disk kotaları"], a: 1 },
            { q: "setuid bitinin sayısal değeri nedir ve örnek?", opts: ["1000, chmod 1755", "2000, chmod 2755", "4000, chmod 4755", "7777"], a: 2 },
            { q: "systemd bir servise override eklemek için önerilen yöntem?", opts: ["Dosyayı /etc/systemd/system/override.conf'a elle yazmak", "systemctl edit servis", "servisi silip yeniden eklemek", "systemctl override true"], a: 1 },
            { q: "journalctl ile sadece son boot loglarını görmek için?", opts: ["journalctl -k", "journalctl -b", "journalctl --last", "journalctl -u boot"], a: 1 },
            { q: "cgroups v2'de CPU limiti ayarlamak için hangi dosya kullanılır?", opts: ["cpu.shares", "cpu.max", "cpuset.cpus", "cpu.limit"], a: 1 },
            { q: "LVM'de bir logical volume'u online büyütmek (ext4) için doğru adım?", opts: ["lvreduce", "lvextend -r", "pvremove", "vgnew"], a: 1 },
            { q: "İleri seviye network debug için tüm paketleri 443 portunda yakalamak?", opts: ["tcpdump port 443", "tcpdump -i any port 443", "tcpdump -w 443.pcap", "iptables -L"], a: 1 },
            { q: "strace komutunun amacı?", opts: ["Disk izleme", "Sistem çağrılarını izlemek/debug etmek", "Kernel modülü yüklemek", "Şifrelemek"], a: 1 },
            { q: "Kernel mesajlarını görmek için yaygın komut?", opts: ["dmesg", "klog", "kernlog", "syslog show"], a: 0 },
            { q: "DNS çözümleme süresini arttıran /etc/nsswitch.conf satırı hangisidir?", opts: ["hosts: files dns", "hosts: dns files", "nameserver 8.8.8.8", "resolver: files"], a: 1 },
            { q: "Bir servisi anında yeniden başlatmak ve bağımlılarını da etkilemek için?", opts: ["systemctl reload", "systemctl restart --all", "systemctl restart --force", "systemctl restart --job-mode=replace-irreversibly"], a: 3 },
            { q: "Swap kullanımını görmek için hızlı komut?", opts: ["free -h", "df -h", "vmstat -s", "swapon -s"], a: 0 },
            { q: "Auditd ile belirli bir dosyayı izlemek için hangi araç kullanılır?", opts: ["auditwatch", "auditctl -w /dosya -p war", "auditd add", "audit -f"], a: 1 },
            { q: "sysctl ile kalıcı kernel parametresi eklemek için nereye yazılır?", opts: ["/etc/sysctl.conf veya /etc/sysctl.d/*.conf", "/boot/grub.cfg", "/etc/hosts", "/etc/environment"], a: 0 },
            { q: "Fail2ban yasaklı IP'leri görmek için?", opts: ["fail2ban-client status <jail>", "iptables -J fail", "ban list", "ufw list"], a: 0 },
            { q: "SSD için noop/cfq yerine önerilen scheduler nedir (güncel kernel)?", opts: ["cfq", "deadline", "bfq", "none/mq-deadline"], a: 3 },
            { q: "Yüksek CPU kullanan işlemin hangi syscallde takıldığını görmek için?", opts: ["lsof -p PID", "strace -p PID", "top -p PID", "free -m"], a: 1 },
            { q: "ip route add 10.0.0.0/24 via 192.168.1.1 komutu ne yapar?", opts: ["Yeni default gateway ekler", "10.0.0.0/24 ağı için 192.168.1.1 üzerinden statik route ekler", "VPN açar", "ARP ekler"], a: 1 }
        ];
const linux_50 = [
            { q: "Linux'ta bir işlem 'D' (uninterruptible sleep) state'indeyse en olası sebep nedir?", opts: ["IO bekliyor", "CPU spin lock", "Zombie process", "Memory leak"], a: 0 },
            { q: "Bir dosyanın inode numarasını görmek için kullanılan komut?", opts: ["ls -i", "stat -c %u", "df -i", "inodectl"], a: 0 },
            { q: "systemd servis loglarını sadece o servise özel filtrelemek için doğru komut?", opts: ["journalctl", "journalctl -u <servis>", "systemctl status --all", "logcat -u"], a: 1 },
            { q: "SELinux 'Enforcing' moddaysa ne olur?", opts: ["Hiçbir şey yapmaz", "Sadece log tutar", "Policy ihlallerini engeller", "Kapanır"], a: 2 },
            { q: "Bir process zombie durumuna nasıl gelir?", opts: ["Parent öldü", "Child öldü ve parent wait() çağırmadı", "CPU %100", "OOM-killer çağrıldı"], a: 1 },
            { q: "Linux'ta /proc directory neyi temsil eder?", opts: ["Sadece loglar", "Kernel kaynak kodu", "Sanal dosya sistemi, kernel ve process bilgisi", "User home dizinleri"], a: 2 },
            { q: "Hard link oluşturmak için komut?", opts: ["ln -s kaynak hedef", "ln kaynak hedef", "link source dest", "mkdir -h"], a: 1 },
            { q: "Swap alanını anlık kullanım ile görmek için?", opts: ["top", "free -h", "df -h", "swapon -a"], a: 1 },
            { q: "Linux'ta file descriptor sınırını görmek için?", opts: ["ulimit -n", "limit -fd", "sysctl -p", "fdstat"], a: 0 },
            { q: "Bir process'i tamamen arka planda detach etmek için hangi komut uygundur?", opts: ["&", "nohup <cmd> &", "bg", "fg"], a: 1 },
            { q: "Bir diskin okuma-yazma hızını test etmek için en çok kullanılan araç?", opts: ["dd", "md5sum", "lshw", "uname"], a: 0 },
            { q: "Sabit IP ayarı hangi dosyadan yapılır? (Debian/Ubuntu)", opts: ["/etc/resolv.conf", "/etc/network/interfaces", "/etc/interfaces.conf", "/etc/static/ip"], a: 1 },
            { q: "DNS cache flush için sistemd temelli distrolarda doğru komut?", opts: ["systemd-resolve --flush-caches", "dnsflush", "systemctl flush dns", "clear dns"], a: 0 },
            { q: "Linux'ta kernel parametrelerini runtime değiştirmek için?", opts: ["sysctl", "uname -all", "kernelctl", "dmesg -k"], a: 0 },
            { q: "System load average 5, CPU 2 core. Bu ne anlama gelir?", opts: ["CPU idle", "Sistem aşırı boş", "Load CPU core sayısından fazla → yoğunluk var", "RAM bitmiş"], a: 2 },
            { q: "Bir process'i belirli bir CPU core’una pinlemek için?", opts: ["taskset", "cpuset", "pset", "affinityctl"], a: 0 },
            { q: "Linux'ta bir dosyayı exectuable yapmak?", opts: ["chmod +x", "chmod +w", "chown exec", "execmod"], a: 0 },
            { q: "Vim içinde kaydedip çıkmanın kısayolu?", opts: [":exit", ":q", ":wq", ":close"], a: 2 },
            { q: "Bir servisin otomatik başlama durumunu görmek?", opts: ["systemctl enabled <servis>", "systemctl is-enabled <servis>", "service start", "chkconfig"], a: 1 },
            { q: "Kernel ring buffer logları hangi komutla görülür?", opts: ["dmesg", "syslog", "journalctl", "kmsg"], a: 0 },
            { q: "Bir binary'nin hangi library'lere bağlı olduğunu görmek için?", opts: ["ldd", "liblist", "ls -l", "ldconfig"], a: 0 },
            { q: "Strace ne işe yarar?", opts: ["Network paket dinler", "CPU profilleme", "System call ve sinyalleri izleme", "FAT32 diskleri mount etme"], a: 2 },
            { q: "Disk kullanımını ağaç olarak göstermek için en uygun komut?", opts: ["treefs", "df -T", "ncdu", "mount —graph"], a: 2 },
            { q: "SSH brute-force saldırılarını engellemek için en bilinen araç?", opts: ["fail2ban", "selinux", "iptables-save", "sshkeygen"], a: 0 },
            { q: "ext4 dosya sistemi ne tür journaling yapar?", opts: ["Metadata-only", "Data + Metadata", "Hiç journaling yapmaz", "Read-only journal"], a: 1 },
            { q: "NTP senkron durumu hangi komutla görülür?", opts: ["ntpstat", "time sync", "chronycheck", "clockctl"], a: 0 },
            { q: "Bir process çok RAM yiyorsa OOM-killer'nin hedef seçme kriteri nedir?", opts: ["CPU kullanımı", "oom_score", "uptime", "nice değeri"], a: 1 },
            { q: "SSH’da key bazlı giriş için public key nereye eklenir?", opts: ["~/.ssh/private_keys", "/etc/ssh/ssh.conf", "~/.ssh/authorized_keys", "/usr/share/keys"], a: 2 },
            { q: "Bir mount'un hangi process tarafından bloklandığını görmek için?", opts: ["lsof", "mount -p", "dmsetup", "blkmon"], a: 0 },
            { q: "tmpfs ne tür bir dosya sistemi?", opts: ["Disk bazlı", "RAM bazlı", "Sadece read-only", "Network bazlı"], a: 1 },
            { q: "systemd timer ile cron farkı nedir?", opts: ["Cron daha modern", "Systemd timer dependency-aware ve unit bazlı", "Cron daha güvenli", "Timer log tutmaz"], a: 1 },
            { q: "Bir process zombie’yse nasıl temizlenir?", opts: ["kill -9", "parent process’i öldürmek veya wait()", "reboot", "swap arttırmak"], a: 1 },
            { q: "Linux'ta network interface bilgisi için hangi komut modern standarttır?", opts: ["ifconfig", "ip addr", "netinfo", "lsnet"], a: 1 },
            { q: "SSH bağlantısında 'Too many authentication failures' hatası ne demek?", opts: ["IP blocked", "Client too many identities deniyor", "Server dolu", "Firewall 80 kapalı"], a: 1 },
            { q: "Core dump dosyalarını etkinleştirmek için?", opts: ["ulimit -c unlimited", "dumpctl enable", "cored --on", "sysdump"], a: 0 },
            { q: "Bir LVM volume’u genişletmek için doğru sıra?", opts: ["mkfs → lvextend", "lvextend → resize2fs", "resize2fs → lvextend", "lvcreate → lvresize"], a: 1 },
            { q: "SSH port değiştirmek hangi dosyada yapılır?", opts: ["/etc/ssh/sshd_config", "/etc/ssh/ssh_config", "/etc/security/ports", "/usr/local/ssh/ports"], a: 0 },
            { q: "Bir kullanıcıya geçmek için hangi komut kullanılır?", opts: ["su", "sudo -su user", "login user", "su - user"], a: 3 },
            { q: "cron job logları genelde nereye düşer?", opts: ["/var/log/cron", "/var/log/messages", "/etc/cron/logs", "/var/lib/cron"], a: 0 },
            { q: "Bir process'in hangi portu dinlediğini görmek için?", opts: ["netstat -tulpn", "ping -l", "traceroute", "watchport"], a: 0 },
            { q: "chmod 755 hangi anlamdadır?", opts: ["rwxr--r--", "rwxr-xr-x", "rw-rw-rw", "r--r--r--"], a: 1 },
            { q: "Kernel modüllerini yüklemek için?", opts: ["modprobe", "modload", "kload", "insmodctl"], a: 0 },
            { q: "Bir process'in memory haritasını görmek için?", opts: ["cat /proc/<pid>/maps", "ps mem", "top -m", "lscpu"], a: 0 },
            { q: "Time zone değiştirmek için önerilen yöntem?", opts: ["date --setzone", "ln -sf /usr/share/zoneinfo/... /etc/localtime", "tzutil", "clockctl"], a: 1 },
            { q: "Bir dosyada satır sayısı bulmak için?", opts: ["wc -l", "count -l", "grep -c total", "awk --lines"], a: 0 },
            { q: "Bir kernel parametresini reboot olmadan değiştirmek için?", opts: ["sysctl -w", "kernelctl", "update-kern", "kset"], a: 0 },
            { q: "Bir process'i SIGTERM ile sonlandırmak için?", opts: ["kill -15", "kill -9", "killall -f", "stop -t"], a: 0 },
            { q: "Bir disk mount edildiğinde fstab'ın kontrol edilmesini sağlayan komut?", opts: ["mount -a", "fstab-check", "autofs --reload", "mdadm mount"], a: 0 },
            { q: "Linux'ta hostname değiştirmek için modern komut?", opts: ["hostnamectl set-hostname", "hostctl set", "nmcli hostname", "sysnamectl"], a: 0 }
        ];
const docker_basic = [
            { q: "docker build -t komutu ne yapar?", opts: ["Container başlatır", "İmaj oluşturur ve etiketler", "Volume oluşturur", "Registry açar"], a: 1 },
            { q: "docker run -p 8080:80 ifadesinde 8080 neyi temsil eder?", opts: ["Container portu", "Host portu", "Docker bridge portu", "Volume adı"], a: 1 },
            { q: "Tüm konteynerleri (çalışan/duran) listelemek için?", opts: ["docker ps", "docker ps -a", "docker ls", "docker list all"], a: 1 },
            { q: "docker rm ile docker rmi farkı nedir?", opts: ["Fark yok", "rm konteyner, rmi imaj siler", "rmi konteyner siler", "rm registry siler"], a: 1 },
            { q: "Logları takip etmek için doğru komut?", opts: ["docker tail", "docker logs", "docker logs -f", "docker watch logs"], a: 2 },
            { q: "Çalışan konteynerde shell açmak için?", opts: ["docker open", "docker attach -n", "docker exec -it <id> sh/bash", "docker connect"], a: 2 },
            { q: "Dockerfile'da ADD ile COPY farkı?", opts: ["Fark yok", "ADD uzak URL/tar açabilir, COPY sadece kopyalar", "COPY sıkıştırır", "ADD sadece klasör"], a: 1 },
            { q: ".dockerignore dosyasının amacı?", opts: ["Gizli dosya saklamak", "Build context'e dahil olmayacak dosyaları dışlamak", "Registry seçmek", "Network ayarı"], a: 1 },
            { q: "Varsayılan compose dosya adı?", opts: ["docker-compose.yml", "compose.yaml", "dockerfile", "docker-compose.txt"], a: 0 },
            { q: "ENTRYPOINT vs CMD için doğru ifade?", opts: ["ENTRYPOINT argüman, CMD ana komut", "ENTRYPOINT ana komut, CMD varsayılan argüman/komut", "İkisi de yok sayılır", "Sadece ENTRYPOINT çalışır"], a: 1 },
            { q: "docker stop ile docker kill farkı?", opts: ["Stop SIGTERM, Kill SIGKILL gönderir", "Fark yok", "Kill daha yavaş", "Stop sadece pause eder"], a: 0 },
            { q: "docker pull ne yapar?", opts: ["Container başlatır", "İmajı registry'den indirir", "Volume mount eder", "Network oluşturur"], a: 1 },
            { q: "Ortam değişkenlerini dosyadan yüklemek için run komutunda?", opts: ["--env-file file.env", "--envs file.env", "--load-env file.env", "--var-file file.env"], a: 0 },
            { q: "İmajları listelemek için?", opts: ["docker list images", "docker images", "docker show", "docker ls img"], a: 1 },
            { q: "Kullanılmayan dangling imajları temizlemek için?", opts: ["docker image prune", "docker system stop", "docker clean images", "docker prune all"], a: 0 },
            { q: "Host dizinini konteynere bağlamak için doğru söz dizimi?", opts: ["-v host:container", "-v container:host", "--vol container host", "-m host:container"], a: 0 },
            { q: "Konteynerden dosya kopyalamak için?", opts: ["docker copy", "docker cp <container>:path dest", "docker scp", "docker export"], a: 1 },
            { q: "Varsayılan ağ türü nedir?", opts: ["host", "none", "bridge", "macvlan"], a: 2 },
            { q: "Exited durumda konteyneri yeniden başlatmak için?", opts: ["docker restart --new", "docker start <id>", "docker run --again", "docker build"], a: 1 },
            { q: "Arka planda çalıştırmak için hangi flag gerekir?", opts: ["--tty", "--rm", "-d", "-it"], a: 2 }
        ];
const docker_intermediate = [
            { q: "Multi-stage build'in temel amacı nedir?", opts: ["Port açmak", "İmaj boyutunu küçültmek ve derleme bağımlılıklarını ayırmak", "Network hızını artırmak", "Registry değiştirmek"], a: 1 },
            { q: "Dockerfile HEALTHCHECK ne işe yarar?", opts: ["Logları temizler", "Container health durumunu raporlar", "Port açar", "Volume oluşturur"], a: 1 },
            { q: "Varsayılan compose ağı nasıl adlandırılır?", opts: ["default", "<proje>_default", "bridge_default", "compose_net"], a: 1 },
            { q: "docker compose up --scale api=3 ne yapar?", opts: ["3 ağ oluşturur", "api servisini 3 replika çalıştırır", "3 volume ekler", "Yalnızca build eder"], a: 1 },
            { q: "Log driver'ı değiştirmek için run sırasında hangi flag kullanılır?", opts: ["--logger", "--log-driver", "--driver-log", "--log"], a: 1 },
            { q: "Bind mount ve volume farkı için doğru ifade?", opts: ["İkisi de hosttan bağımsız", "Bind host dizinini bağlar, volume Docker yönetimli dizindir", "Volume her zaman read-only", "Bind sadece Windows'ta"], a: 1 },
            { q: "docker exec ile docker attach farkı?", opts: ["Exec yeni işlem başlatır, attach mevcut sürece bağlanır", "Fark yok", "Attach logları siler", "Exec sadece root çalışır"], a: 0 },
            { q: "Restart policy 'on-failure' neye göre çalışır?", opts: ["Her zaman", "Sadece manuel", "Çıkış kodu 0 olmayan durumlarda yeniden başlatır", "CPU yüksekse"], a: 2 },
            { q: "Container IP adresini hızlıca almak için hangi komut?", opts: ["docker ip", "docker inspect -f '{{.NetworkSettings.IPAddress}}' <id>", "docker net show", "docker ps --ip"], a: 1 },
            { q: "Build cache'i kırmak için en basit bayrak?", opts: ["--no-cache", "--fresh", "--nocache", "--skip-cache"], a: 0 },
            { q: "docker compose depends_on varsayılan davranışı?", opts: ["Health bekler", "Sadece start sırası (health'i beklemez)", "Logları takip eder", "CPU sınırlar"], a: 1 },
            { q: "docker stats komutu ne gösterir?", opts: ["Network haritası", "Gerçek zamanlı kaynak kullanımı", "Imaj boyutu", "Registry listesi"], a: 1 },
            { q: "Dockerfile ARG ve ENV farkı?", opts: ["ARG build-time, ENV runtime'da da kalır", "ENV sadece build-time", "ARG kalıcıdır", "Fark yok"], a: 0 },
            { q: "Private registry'ye login olmak için?", opts: ["docker auth", "docker login <registry>", "docker connect registry", "docker registry login"], a: 1 },
            { q: "İmajı tar arşivi olarak kaydetmek için hangi komut?", opts: ["docker archive", "docker save", "docker export", "docker bundle"], a: 1 },
            { q: "Konteyner dosya sistemini katmansız tar olarak almak için?", opts: ["docker pull", "docker export", "docker cp -a", "docker image save"], a: 1 },
            { q: "Build context'i küçültmek için temel araç?", opts: [".dockerignore kullanmak", "docker slim", "docker cache", "docker prune"], a: 0 },
            { q: "Varsayılan volume driver'ı nedir?", opts: ["nfs", "local", "azurefile", "efs"], a: 1 },
            { q: "Tüm durdurulmuş konteynerleri silmek için?", opts: ["docker stop all", "docker rm -a", "docker container prune", "docker clean"], a: 2 },
            { q: "Compose'da bir servise özel network alias eklemek için nereye yazılır?", opts: ["services.<svc>.networks[].aliases", "root düzeye", "Dockerfile'a", "Volume altına"], a: 0 }
        ];
const docker_advanced = [
            { q: "Rootless Docker'ın temel avantajı nedir?", opts: ["Daha hızlı build", "Daemon'u non-root çalıştırarak yetki azaltmak", "Daha büyük imaj", "Swarm kurmak"], a: 1 },
            { q: "Kernel yetkilerini minimuma indirmek için hangi flag kullanılır?", opts: ["--cap-add", "--cap-drop", "--privileged", "--userns"], a: 1 },
            { q: "Custom seccomp profili uygulamak için run'da hangi seçenek kullanılır?", opts: ["--seccomp-profile file.json", "--security-opt seccomp=file.json", "--security file", "--seccomp true"], a: 1 },
            { q: "Konteyner kök dosya sistemini salt-okunur yapmak için?", opts: ["--read-only", "--immutable", "--rofs", "--no-write"], a: 0 },
            { q: "CPU limitini 1.5 core ile sınırlamak için?", opts: ["--cpu=1.5", "--cpus 1.5", "--limit-cpu 1.5", "--quota 1.5"], a: 1 },
            { q: "Belleği 512MB ile sınırlamak için doğru bayrak?", opts: ["--mem 512", "--memory 512m", "--ram 512", "--mem-limit 512"], a: 1 },
            { q: "no-new-privileges özelliği nasıl açılır?", opts: ["--security-opt no-new-privileges:true", "--no-priv", "--drop-priv", "--seccomp nnp"], a: 0 },
            { q: "Multi-arch imaj üretmek için hangi araç/komut kullanılır?", opts: ["docker build", "docker buildx build --platform ...", "docker make multi", "docker manifest pull"], a: 1 },
            { q: "Build cache'i remote/pull-push ile paylaşmak için hangi bayraklar kullanılır?", opts: ["--cache-on", "--cache-from / --cache-to", "--cache-share", "--remote-cache"], a: 1 },
            { q: "Content Trust'u açmak için gerekli ortam değişkeni?", opts: ["DOCKER_TRUST=1", "DOCKER_CONTENT_TRUST=1", "DOCKER_VERIFY=1", "CONTENT_TRUST=ON"], a: 1 },
            { q: "Docker Hub rate limitine takılmamak için doğru çözüm?", opts: ["Daha çok pull yapmak", "Auth ile login veya mirror kullanmak", "Pull'u kapatmak", "Disk büyütmek"], a: 1 },
            { q: "Çok host'lu overlay ağ oluşturmak için hangi driver gerekir?", opts: ["bridge", "host", "overlay", "macvlan"], a: 2 },
            { q: "Swarm'da secret'lar container içinde nereye mount edilir?", opts: ["/etc/secrets", "/run/secrets (tmpfs)", "/var/lib/docker", "ENV olarak"], a: 1 },
            { q: "CLI'da imaj güvenlik taraması için hangi komut kullanılabilir?", opts: ["docker scan <image>", "docker virus", "docker audit", "docker secure"], a: 0 },
            { q: "Logları fluentd'ye göndermek için hangi driver seçilir?", opts: ["json-file", "local", "fluentd", "awslogs"], a: 2 },
            { q: "BuildKit'i etkinleştirmek için ortam değişkeni?", opts: ["BUILD_KIT=1", "DOCKER_BUILDKIT=1", "USE_BUILDKIT=true", "KIT=ON"], a: 1 },
            { q: "Çalışan container'a tmpfs mount eklemek için doğru run flag'i?", opts: ["--tmpfs /path", "--mount tmpfs", "--memfs", "--tempfs"], a: 0 },
            { q: "Modern Linux'ta önerilen varsayılan storage driver hangisi?", opts: ["aufs", "devicemapper loop", "overlay2", "zfs"], a: 2 },
            { q: "Konteynerlerin host Docker daemon'una erişimini engellemek için en kritik adım?", opts: ["/var/run/docker.sock'u mount etmemek", "Logları kapatmak", "CPU limitlerini kaldırmak", "Privileged mod açmak"], a: 0 },
            { q: "Küçük runtime imajı üretmek için doğru yaklaşım?", opts: ["Tek stage'de build", "Builder stage'den binary kopyalayıp scratch/alpine ile final stage yapmak", "İmajı zip'lemek", "Registry'de sıkıştırmak"], a: 1 }
        ];
const git_basic = [
            { q: "Yeni bir Git reposu başlatmak için?", opts: ["git init", "git start", "git repo", "git begin"], a: 0 },
            { q: "Değişikliklerin durumunu görmek için?", opts: ["git diff", "git status", "git check", "git show"], a: 1 },
            { q: "İzlenmeyen dosyayı takibe almak için?", opts: ["git commit", "git add dosya", "git push", "git stash"], a: 1 },
            { q: "Commit oluşturmak için doğru komut?", opts: ["git save -m", "git commit -m \"mesaj\"", "git push -m", "git write"], a: 1 },
            { q: "Uzak depo eklemek için?", opts: ["git remote add origin <url>", "git add origin <url>", "git push origin", "git link <url>"], a: 0 },
            { q: "Uzak repoya ilk push için (branch main ise)?", opts: ["git push origin", "git push -u origin main", "git push main", "git upload"], a: 1 },
            { q: "Son commit'i mesajıyla görmek için pratik komut?", opts: ["git show --stat", "git log -1", "git status -1", "git head"], a: 1 },
            { q: "Çalışma alanıyla staged farkını görmek için?", opts: ["git diff --cached", "git diff", "git show", "git status"], a: 0 },
            { q: ".gitignore dosyasının amacı?", opts: ["Logları silmek", "Takip edilmeyecek dosya/desenleri belirtmek", "Commit mesajı yazmak", "Remote eklemek"], a: 1 },
            { q: "Yeni branch oluşturup geçmek için tek komut?", opts: ["git checkout -b feature", "git branch feature && git checkout feature", "git switch", "git new feature"], a: 0 },
            { q: "Branch listesini görmek için?", opts: ["git branches", "git branch", "git show-branch", "git list"], a: 1 },
            { q: "Branch'i başka branche birleştirmek için temel komut?", opts: ["git merge <branch>", "git rebase <branch>", "git join <branch>", "git attach <branch>"], a: 0 },
            { q: "Uzak branch'i yerel branch olarak takip etmek için?", opts: ["git checkout origin/main", "git checkout -b main origin/main", "git fetch main", "git pull main"], a: 1 },
            { q: "Çalışma alanındaki değişiklikleri geçici olarak saklamak için?", opts: ["git stash", "git save", "git hide", "git park"], a: 0 },
            { q: "Son commit'i geri almak ama değişiklikleri çalışma alanında tutmak için?", opts: ["git reset --hard HEAD~1", "git reset --soft HEAD~1", "git reset --mixed HEAD~1", "git revert HEAD"], a: 2 },
            { q: "Son commit'i mesajıyla birlikte tamamen geri almak (değişiklik de silinsin) için?", opts: ["git reset --hard HEAD~1", "git revert HEAD", "git stash drop", "git clean"], a: 0 },
            { q: "Remote'ları listelemek için?", opts: ["git remote -v", "git remotes", "git list remote", "git show remote"], a: 0 },
            { q: "HEAD nedir?", opts: ["Son commit hash'i", "Çalıştığın branch'i işaret eden referans", "Remote adı", "Stash adı"], a: 1 },
            { q: "Var olan commit'e dokunmadan yeni bir düzeltme commit'i eklemek için?", opts: ["git amend", "git revert <hash>", "git undo", "git redo"], a: 1 },
            { q: "Branch ismini değiştirmek için (geçerli branch'teyken)?", opts: ["git rename", "git branch -m yeni-ad", "git switch -m", "git move branch"], a: 1 }
        ];
const git_intermediate = [
            { q: "Merge yerine rebase kullanmanın temel sonucu nedir?", opts: ["Commitleri siler", "Lineer tarih oluşturur, commitleri yeniden yazar", "Remote'u kapatır", "Branch'i siler"], a: 1 },
            { q: "git cherry-pick <hash> ne yapar?", opts: ["Commit'i siler", "Seçili commit'i mevcut branche uygular", "Yeni branch açar", "Stash oluşturur"], a: 1 },
            { q: "git reset --mixed HEAD~1 ne yapar?", opts: ["Çalışma alanını siler", "Son commit'i kaldırır, değişiklikleri çalışma alanında ve unstaged bırakır", "Commit'i revert eder", "Sadece staging'i korur"], a: 1 },
            { q: "git revert <hash> ne üretir?", opts: ["Commit'i siler", "Ters değişiklik içeren yeni commit ekler", "Branch'i siler", "Stash oluşturur"], a: 1 },
            { q: "Annotate tag oluşturmak için doğru komut?", opts: ["git tag v1", "git tag -a v1 -m \"mesaj\"", "git tag --note v1", "git tag -s v1 -m"], a: 1 },
            { q: "git stash apply ile git stash pop farkı?", opts: ["Fark yok", "apply uygular, pop uygular ve stash kaydını siler", "apply siler, pop uygular", "apply merge yapar"], a: 1 },
            { q: "git reflog neyi gösterir?", opts: ["Remote branch listesi", "HEAD hareketlerinin geçmişi", "Tag listesi", "Credential cache"], a: 1 },
            { q: "git clean -fd komutu ne yapar?", opts: ["Staged dosyaları siler", "Untracked dosya ve dizinleri zorla temizler", "Commit'leri temizler", "Cache'i sıfırlar"], a: 1 },
            { q: "Son 3 commit'i squashlamak için hangi komutla başlarsın?", opts: ["git rebase -i HEAD~3", "git merge --squash", "git squash 3", "git commit --squash"], a: 0 },
            { q: "Merge conflict sonrası ilk adım?", opts: ["git reset --hard", "Çakışan dosyaları düzeltip git add yapmak", "git revert", "git stash"], a: 1 },
            { q: "Staged ile son commit farkını görmek için?", opts: ["git diff", "git diff --cached", "git status -v", "git show --cached"], a: 1 },
            { q: "git blame'in amacı?", opts: ["Commit mesajı düzeltmek", "Satır bazlı yazar/tarih bilgisini göstermek", "Branch silmek", "Tag eklemek"], a: 1 },
            { q: "Var olan branch'in upstream'ini sonradan ayarlamak için?", opts: ["git upstream set", "git branch --set-upstream-to=origin/feature feature", "git push --set", "git track"], a: 1 },
            { q: "git fetch ile git pull farkı?", opts: ["Pull sadece fetch yapar", "Fetch indirir, pull indirip merge/rebase eder", "Fark yok", "Fetch commit siler"], a: 1 },
            { q: "Submodule'ları ilk kez çekmek/güncellemek için doğru komut?", opts: ["git submodule update --init --recursive", "git submodule install", "git pull --sub", "git fetch --submodule"], a: 0 },
            { q: "git bisect'in amacı?", opts: ["Tag oluşturmak", "Hatalı commit'i ikili arama ile bulmak", "Branch temizlemek", "Remote silmek"], a: 1 },
            { q: "Untracked dosyaları da stash'e eklemek için hangi bayrak?", opts: ["git stash -a", "git stash -u", "git stash --all", "git stash add"], a: 1 },
            { q: "Commit grafiğini kısaca görmek için pratik komut?", opts: ["git graph", "git log --oneline --graph --decorate --all", "git history", "git show graph"], a: 1 },
            { q: "Son commit mesajını değiştirip içeriği aynı tutmak için?", opts: ["git commit --amend", "git revert HEAD", "git reset --hard", "git amend-msg"], a: 0 },
            { q: "Yerel branch adını değiştirmek için (branch'ta değilken)?", opts: ["git rename old new", "git branch -m old new", "git move old new", "git switch -m old new"], a: 1 }
        ];
const git_advanced = [
            { q: "Git hook'ları varsayılan olarak nerede bulunur?", opts: [".git/hooks", ".hooks", ".git/config", "/etc/git/hooks"], a: 0 },
            { q: "Commit'i GPG ile imzalamak için hangi bayrak kullanılır?", opts: ["git commit -S -m \"msg\"", "git commit --signoff", "git commit --verify", "git commit --secure"], a: 0 },
            { q: "Dosyanın sadece belirli kısımlarını stage etmek için hangi komut kullanılır?", opts: ["git add file", "git add -p file", "git stage parts", "git patch add"], a: 1 },
            { q: "Büyük binary dosyaları takip etmek için en doğru yaklaşım?", opts: ["Repo'ya normal eklemek", "Git LFS kullanmak", "Tar.gz'a koymak", "Submodule'a taşımak"], a: 1 },
            { q: "Son N commitlik sığ klon için hangi bayrak kullanılır?", opts: ["--shallow", "--depth 1", "--small", "--thin"], a: 1 },
            { q: "git rebase --onto yeni eski branch ne yapar?", opts: ["Tag ekler", "branch'teki eski sonrası commitleri yeni tabana taşıyarak tarihi yeniden yazar", "Merge açar", "Stash temizler"], a: 1 },
            { q: "rerere özelliği ne işe yarar?", opts: ["Remoteleri düzenler", "Tekrarlayan conflict çözümünü kaydedip otomatik uygular", "Reflog'u siler", "Rebase hızlandırır"], a: 1 },
            { q: "Geçmişten gizli dosyayı tamamen silmek için modern ve hızlı araç?", opts: ["git filter-branch", "git filter-repo", "git gc", "git prune-file"], a: 1 },
            { q: "git fetch --prune ne yapar?", opts: ["Yerel branch'i siler", "Remote'ta silinmiş branch'lerin izlerini temizler", "Tag'leri siler", "GC çalıştırır"], a: 1 },
            { q: "Aynı repo için ikinci çalışma dizini açmak için hangi komut kullanılır?", opts: ["git clone . ../copy", "git worktree add ../path branch", "git branch --copy", "git subtree add"], a: 1 },
            { q: "Monorepo'da sadece belirli klasörü çekmek için hangi özellik kullanılır?", opts: ["Submodule", "Sparse checkout (git sparse-checkout set ...)", "Shallow clone", "Filter-branch"], a: 1 },
            { q: "Whitespace değişikliklerini yok sayarak blame almak için hangi flag?", opts: ["git blame -c", "git blame -w", "git blame --all", "git blame --thin"], a: 1 },
            { q: "Hatalı commit'i otomatik test çalıştırarak bulmak için?", opts: ["git search", "git bisect run <komut>", "git bisect find", "git blame --run"], a: 1 },
            { q: "Staged değişiklikleri son commit'e mesajı değiştirmeden eklemek için?", opts: ["git commit --amend --no-edit", "git commit --append", "git add --amend", "git push --amend"], a: 0 },
            { q: "Fixup/squash commitlerini otomatik sıralamak için akış nedir?", opts: ["git commit --fixup <hash> ardından git rebase -i --autosquash", "git squash --auto", "git rebase --auto", "git fixup --rebase"], a: 0 },
            { q: "İmzalı tag oluşturmak için doğru komut?", opts: ["git tag v1.0", "git tag -s v1.0 -m \"msg\"", "git tag --signoff v1.0", "git tag --gpg v1.0"], a: 1 },
            { q: "git gc komutu ne yapar?", opts: ["Branch siler", "Repo'yu sıkıştırır/çöpleri temizler", "Remote'ları günceller", "Commit mesajı değiştirir"], a: 1 },
            { q: "Tüm referansları birebir başka remote'a aktarmak için hangi push kullanılır?", opts: ["git push --all", "git push --mirror", "git push --force", "git push --tags"], a: 1 },
            { q: "History rewrite sonrası daha güvenli force push için önerilen bayrak?", opts: ["--force", "--force-with-lease", "--hard-push", "--rewrite"], a: 1 },
            { q: "Geçerli HEAD'in tam hash'ini almak için hangi komut kullanılır?", opts: ["git hash", "git rev-parse HEAD", "git show-hash", "git head --id"], a: 1 }
        ];
const network_basic = [
            { q: "OSI modelinde 3. katman hangisidir?", opts: ["Uygulama", "Oturum", "Ağ (Network)", "Veri Bağı (Data Link)"], a: 2 },
            { q: "TCP hangi katmanda çalışır?", opts: ["Taşıma", "Veri Bağı", "Fiziksel", "Sunum"], a: 0 },
            { q: "HTTP varsayılan portu nedir?", opts: ["21", "22", "80", "110"], a: 2 },
            { q: "HTTPS hangi protokolün güvenli halidir?", opts: ["FTP", "SMTP", "HTTP", "IMAP"], a: 2 },
            { q: "DNS kaydı 'A' neyi çözer?", opts: ["IPv6", "Mail sunucusu", "IPv4", "Alias"], a: 2 },
            { q: "Ping hangi protokolü kullanır?", opts: ["TCP", "UDP", "ICMP", "ARP"], a: 2 },
            { q: "Subnet maskesi 255.255.255.0 hangi CIDR'a eşittir?", opts: ["/16", "/24", "/25", "/30"], a: 1 },
            { q: "MAC adresi hangi katmanda kullanılır?", opts: ["Fiziksel", "Veri Bağı", "Ağ", "Taşıma"], a: 1 },
            { q: "DHCP'nin görevi nedir?", opts: ["IP dağıtmak", "Şifrelemek", "Routing yapmak", "Port yönlendirmek"], a: 0 },
            { q: "NAT'ın temel amacı?", opts: ["Şifreleme", "IP adreslerini dönüştürmek", "DNS çözmek", "Kablosuz yayın"], a: 1 },
            { q: "SSH varsayılan portu?", opts: ["21", "22", "23", "25"], a: 1 },
            { q: "SMTP hangi portta (varsayılan TLS'siz)?", opts: ["25", "53", "110", "143"], a: 0 },
            { q: "IMAP hangi tip protokoldür?", opts: ["Dosya transferi", "E-posta alma", "Web sunucu", "VPN"], a: 1 },
            { q: "Traceroute'un amacı nedir?", opts: ["Gecikmeyi ölçmek", "Geçilen router'ları görmek", "Port taramak", "DNS çözmek"], a: 1 },
            { q: "Switch hangi katmanda çalışır (temel L2)?", opts: ["3", "2", "4", "7"], a: 1 },
            { q: "Router'ın görevi?", opts: ["Kablosuz sinyal güçlendirmek", "Ağlar arası yönlendirme", "MAC tablosu tutmak", "Şifreleme"], a: 1 },
            { q: "Private IP aralığı değildir?", opts: ["10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16", "8.8.8.0/24"], a: 3 },
            { q: "ARP ne yapar?", opts: ["MAC'i IP'ye çevirir", "IP'yi MAC'e çevirir", "DNS kayıtlarını listeler", "SSH anahtarı üretir"], a: 1 },
            { q: "UDP'nin özelliği?", opts: ["Bağlantı tabanlı", "Teslim garantisi", "Hızlı ve connectionless", "Akış kontrolü var"], a: 2 },
            { q: "FTP pasif modda veri portu kim belirler?", opts: ["İstemci", "Sunucu", "DNS", "Router"], a: 1 }
        ];
const network_intermediate = [
            { q: "CIDR 10.0.0.0/20 ağı kaç IP içerir?", opts: ["1024", "2048", "4096", "8192"], a: 2 },
            { q: "VLAN'lar hangi katmanda izole eder?", opts: ["L1", "L2", "L3", "L4"], a: 1 },
            { q: "Inter-VLAN routing için ne gerekir?", opts: ["Layer2 switch", "Router-on-a-stick veya L3 switch", "Hub", "Access point"], a: 1 },
            { q: "Default gateway'nin görevi?", opts: ["DNS çözmek", "Yerel ağ dışı trafiği yönlendirmek", "MAC adresi dağıtmak", "DHCP lease uzatmak"], a: 1 },
            { q: "TCP üçlü el sıkışmada ikinci adım nedir?", opts: ["SYN", "ACK", "SYN-ACK", "FIN"], a: 2 },
            { q: "MTU aşıldığında parçalama yapmayan protokol hangisi?", opts: ["TCP", "UDP", "ICMP", "IPsec"], a: 0 },
            { q: "CIDR 192.168.1.0/26 için broadcast adresi nedir?", opts: ["192.168.1.63", "192.168.1.64", "192.168.1.62", "192.168.1.127"], a: 0 },
            { q: "NAT türlerinden PAT ne yapar?", opts: ["Her iç IP'ye benzersiz public IP", "Port adres çevirisiyle tek IP paylaşımı", "Statik 1:1 çeviri", "ARP cache silme"], a: 1 },
            { q: "DNS CNAME kaydı ne sağlar?", opts: ["Mail yönlendirme", "Alias/kanonik isim yönlendirme", "Reverse lookup", "TXT doğrulama"], a: 1 },
            { q: "Reverse proxy temel faydası?", opts: ["İstemciyi gizlemek", "Sunucuyu gizlemek ve dağıtmak", "DHCP dağıtmak", "Traceroute yapmak"], a: 1 },
            { q: "CIDR /30 kaç kullanılabilir host sağlar?", opts: ["2", "4", "6", "14"], a: 0 },
            { q: "VRRP/HSRP'nin amacı?", opts: ["QoS", "Yüksek erişilebilir varsayılan gateway", "DNS cache", "TLS offload"], a: 1 },
            { q: "NTP hangi port/protokol ile çalışır?", opts: ["123/UDP", "123/TCP", "53/UDP", "443/TCP"], a: 0 },
            { q: "SNMP hangi amaçla kullanılır?", opts: ["Dosya transferi", "Ağ cihazlarından izleme/yorumlama", "Şifreleme", "DHCP dağıtmak"], a: 1 },
            { q: "802.1X neyi sağlar?", opts: ["Kablosuz hız", "Port bazlı kimlik doğrulama", "QoS", "VPN tüneli"], a: 1 },
            { q: "Traceroute Linux'ta varsayılan hangi protokolü kullanır?", opts: ["TCP SYN", "ICMP Echo", "UDP high port", "GRE"], a: 2 },
            { q: "Load balancer'da sticky session sağlamak için yaygın yöntem?", opts: ["HTTPS kapatmak", "Source IP hash veya cookie tabanlı oturum", "MTU artırmak", "BGP kapatmak"], a: 1 },
            { q: "CIDR 172.16.0.0/16 ağını /24'e bölerseniz kaç alt ağ elde edilir?", opts: ["16", "64", "256", "512"], a: 2 },
            { q: "UDP tabanlı DNS isteği tipik boyutu büyürse hangi risk ortaya çıkar?", opts: ["ACK storm", "Fragmentation ve amplification", "SSL error", "MAC flooding"], a: 1 },
            { q: "Site-to-site IPSec tünelde Phase 1 amacı?", opts: ["Veri şifrelemek", "IKE ile karşılıklı kimlik/doğrulama ve SA kurmak", "QoS tanımlamak", "NAT yapmak"], a: 1 }
        ];
const network_advanced = [
            { q: "BGP'de AS_PATH ne işe yarar?", opts: ["QoS tanımlar", "En kısa otonom sistem yolunu listeler", "TLS şifrelemesi sağlar", "DHCP lease dağıtır"], a: 1 },
            { q: "BGP'de loop önleme mekanizması?", opts: ["Split horizon", "AS_PATH kontrolü", "Poison reverse", "TTL 255"], a: 1 },
            { q: "OSPF'de DR/BDR seçimi hangi metrikle yapılır?", opts: ["Router ID en düşük", "Cost en düşük", "Priority en yüksek, eşitse Router ID en yüksek", "MAC adresi"], a: 2 },
            { q: "Anycast kullanımının temel faydası?", opts: ["Tek noktaya sabit trafik", "En yakın node'a yönlendirme ile gecikme düşürmek", "Kapsayıcı network", "VLAN trunk"], a: 1 },
            { q: "Load balancer health check başarısız hedefleri havuzdan çıkarmazsa ilk kontrol?", opts: ["Health check protokol/path/timeout", "BGP policy", "QoS sınıfı", "IPSec phase 1"], a: 0 },
            { q: "DDoS L7 saldırılarına karşı hangi çözüm etkilidir?", opts: ["BGP blackhole", "WAF ve rate limiting", "MTU büyütme", "OSPF cost düşürme"], a: 1 },
            { q: "Segment routing neyi sağlar?", opts: ["L2 VLAN genişletme", "Label tabanlı deterministik yol kontrolü", "DHCP relay", "QoS shaping"], a: 1 },
            { q: "Dual-homed edge BGP'de asymmetric routing sorununda ne yapılabilir?", opts: ["ECMP kapatmak", "MED/LOCAL_PREF ve AS_PATH prepending ayarlamak", "DNS TTL düşürmek", "ARP cache temizlemek"], a: 1 },
            { q: "MPLS L3VPN'de CE ile PE arasında hangi protokol zorunlu?", opts: ["BGP veya başka bir IGP (OSPF/EIGRP/RIP)", "LDP", "RSVP", "VXLAN"], a: 0 },
            { q: "VXLAN VNI kaç bitlik ID kullanır?", opts: ["12", "16", "24", "32"], a: 2 },
            { q: "Zero Trust ağında temel prensip?", opts: ["Ağ içi her şeye tam yetki", "Sürekli kimlik, cihaz ve bağlam doğrulaması", "Tek factor auth", "Statik ACL yeterli"], a: 1 },
            { q: "IKEv2'de Perfect Forward Secrecy için hangi anahtar değişim kullanılır?", opts: ["RSA static", "Diffie-Hellman", "PSK MD5", "SHA1"], a: 1 },
            { q: "Route flapping'i azaltmak için hangi mekanizma kullanılır?", opts: ["Route poisoning", "Route dampening", "Split horizon", "BFD kapatma"], a: 1 },
            { q: "BFD'nin amacı nedir?", opts: ["DNS cache", "Hızlı link arızası tespiti", "QoS marking", "TLS handshake hızlandırma"], a: 1 },
            { q: "EVPN'de Type 2 route neyi taşır?", opts: ["MAC/IP binding", "Multicast grup", "Default route", "Label değerleri"], a: 0 },
            { q: "CDN edge node'larında cache bypass oranını azaltmak için ne yapılır?", opts: ["TTL 0", "Cache key standardizasyonu ve uygun TTL", "BGP prepending", "MTU artırmak"], a: 1 },
            { q: "Firewall'da stateful inspection ne sağlar?", opts: ["Sadece source IP kontrolü", "Bağlantı durum tablosuyla geri dönüş trafiğine izin verme", "Sadece ACL", "NAT loopback"], a: 1 },
            { q: "QoS'da DSCP AF31 hangi sınıfı temsil eder?", opts: ["EF Voice", "AF sınıfı, assured forwarding", "Best effort", "CS0"], a: 1 },
            { q: "IPv6'da SLAAC ne yapar?", opts: ["DNSSEC sağlar", "Router reklamıyla otomatik adres atar", "DHCPv4 lease", "NAT64"], a: 1 },
            { q: "Overlay/underlay ayrımında underlay neyi ifade eder?", opts: ["SSH tüneli", "Fiziksel/temel IP altyapısı", "Uygulama katmanı", "TLS offload"], a: 1 }
        ];
const pro_quiz = [
            { q: "Bir prod Kubernetes cluster'ında node'lar sık sık 'NotReady' oluyor. Pod'lar eviction sonrası farklı node'lara planlanmıyor. İlk bakılacak yer?", opts: ["CNI daemonset logları ve kubelet network plugin durumu", "Ingress controller deployment'ı", "Helm chart values.yaml", "HorizontalPodAutoscaler tanımı"], a: 0 },
            { q: "Terraform state remote backend (S3 + DynamoDB lock) için en güvenli IAM stratejisi?", opts: ["EC2 instance role'a full s3:* yetkisi", "S3'te bucket policy yerine tüm yetkiyi kullanıcılara ver", "Sadece gerekli aksiyonları (GetObject, PutObject, ListBucket) ve dynamodb:UpdateItem ile least privilege", "CLI profiline inline policy ile admin"], a: 2 },
            { q: "Blue/Green deploy sırasında databasede schema değişikliği var. Downtime ve veri kaybını en aza indirmek için hangi yaklaşım doğru?", opts: ["Deploy öncesi eski versiyonu kapat", "Schema'yı geriye uyumlu olacak şekilde önce ekle, app'i sonra taşır, feature flag ile geçiş", "Yeni tabloyu oluşturup eskiyi sil", "Canary trafiği %100'e çıkar, sonra migration"], a: 1 },
            { q: "Prometheus'ta yüksek cardinality'den kaçınmak için hangi label tasarımı doğru?", opts: ["request_path label'ında tam URL path'i tutmak", "user_id'yi label yapmak", "HTTP status kodunu label yapmak", "timestamp'i label yapmak"], a: 2 },
            { q: "GitHub Actions runner'ında cache invalidation sık yaşanıyor. Hangi anahtar stratejisi daha tutarlı?", opts: ["Key olarak sadece 'linux-node' kullanmak", "Key'e checksum of lockfile eklemek, restore-keys ile prefix kullanmak", "Random UUID üretmek", "Her job için farklı key"], a: 1 },
            { q: "EKS'te private cluster çalışırken kubectl erişimi için en pratik ve güvenli çözüm?", opts: ["Master public endpoint açıp 0.0.0.0/0 izin vermek", "Bastion host'tan kubectl proxy", "AWS IAM authenticator + SSM Session Manager tüneli veya VPN", "Kubeconfig'e basic auth user eklemek"], a: 2 },
            { q: "CI pipeline'da gizli değişkenlerin log'a dökülmemesi için ne yapılmalı?", opts: ["Echo ile maskelemek", "Masked secrets özelliğini açmak ve gereksiz debug çıktısını kapatmak", "Secrets'i env yerine arg olarak geçmek", "Secrets'i plaintext repo'ya koymak"], a: 1 },
            { q: "Docker multi-stage build'de production image boyutunu küçültmek için kritik adım?", opts: ["Tüm build'leri tek stage'de yapmak", "Final stage'e yalnızca runtime bağımlılıklarını ve artefactları kopyalamak", "apt-get update'i sonda çalıştırmak", "ENTRYPOINT kaldırmak"], a: 1 },
            { q: "ArgoCD'de drift detection uyarıları sürekli 'outOfSync' veriyor. İlk kontrol?", opts: ["App of Apps modelini kapatmak", "Resource Customization için ignoreDifferences ayarlarını gözden geçirmek", "Git repo'yu public yapmak", "RBAC'i devre dışı bırakmak"], a: 1 },
            { q: "SRE hata bütçesi (error budget) %50 tükendi. En doğru aksiyon?", opts: ["Daha hızlı deploy", "Yeni feature rollout'u yavaşlatıp istikrar iyileştirmelerine öncelik vermek", "Tüm alarmları kapatmak", "Status page'i gizlemek"], a: 1 },
            { q: "AWS ALB + Target Group mimarisinde, health check başarısız oranı yüksekse en önce bakılması gereken?", opts: ["Route 53 policy", "Target group health check path/interval/timeout ve security group izinleri", "S3 bucket policy", "VPC endpoint"], a: 1 },
            { q: "Vault kullanırken uygulama pod'una secret nasıl en güvenli taşınır?", opts: ["Secret'ı image içine bake etmek", "Env var olarak plaintext yazmak", "Vault Agent sidecar + Kubernetes auth method ile otomatik yenileme", "Secret'ı configmap'e yazmak"], a: 2 },
            { q: "Production PostgreSQL için sürdürülebilir yedekleme stratejisi?", opts: ["Sadece haftalık dump", "pg_dump daily, WAL archiving ve periyodik restore testi", "Snapshot almamak", "Sadece read replica tutmak"], a: 1 },
            { q: "Microservice'ler için log standardizasyonu yapılırken en iyi pratik?", opts: ["Her serviste farklı format", "Plain text random", "Structured JSON log, korelasyon ID eklemek, stdout'a yazmak", "Logları diske yazıp arşivlemek"], a: 2 },
            { q: "Kubernetes'te PodSecurityStandards (baseline/restricted) gereksinimi var. Uygulama nasıl enforce edilir?", opts: ["kubectl apply -f pod.yaml", "PSA (Pod Security Admission) label'larını namespace'e eklemek veya OPA/Gatekeeper/PSP eşdeğeri policy kullanmak", "Toleration eklemek", "NodeSelector kaldırmak"], a: 1 },
            { q: "CI/CD'de supply chain güvenliği için en etkili adım?", opts: ["Docker Hub'dan rastgele image çekmek", "SBOM üretmek, imaj imzalamak (Cosign/Sigstore) ve admission policy ile doğrulamak", "Root olarak çalıştırmak", "Cache'i kapatmak"], a: 1 }
        ];
const all_mixed = [].concat(linux_basic, linux_intermediate, linux_advanced, linux_50, docker_basic, docker_intermediate, docker_advanced, git_basic, git_intermediate, git_advanced, network_basic, network_intermediate, network_advanced);
window.QUIZ_DATA = {
  "linux-basic": { title: "Linux Temel Seviye Quiz", questions: linux_basic },
  "linux-intermediate": { title: "Linux Orta Seviye Quiz", questions: linux_intermediate },
  "linux-advanced": { title: "Linux İleri Seviye Quiz", questions: linux_advanced },
  "linux-50": { title: "Linux 50 Soru", questions: linux_50 },
  "docker-basic": { title: "Docker Temel Seviye Quiz", questions: docker_basic },
  "docker-intermediate": { title: "Docker Orta Seviye Quiz", questions: docker_intermediate },
  "docker-advanced": { title: "Docker İleri Seviye Quiz", questions: docker_advanced },
  "git-basic": { title: "Git Temel Seviye Quiz", questions: git_basic },
  "git-intermediate": { title: "Git Orta Seviye Quiz", questions: git_intermediate },
  "git-advanced": { title: "Git İleri Seviye Quiz", questions: git_advanced },
  "network-basic": { title: "Network Temel Seviye Quiz", questions: network_basic },
  "network-intermediate": { title: "Network Orta Seviye Quiz", questions: network_intermediate },
  "network-advanced": { title: "Network İleri Seviye Quiz", questions: network_advanced },
  "pro-quiz": { title: "Pro Quiz (Karışık)", questions: pro_quiz },
  "all": { title: "Tüm Konular (Karışık)", questions: all_mixed }
};
})();
